// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestService.proto

package com.example.grpc;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string sex = 4;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 4;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();
}
